apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
stringData:
  TOKEN: {{ .Values.secrets.TOKEN | quote }}
  CLIENT_ID: {{ .Values.secrets.CLIENT_ID | quote }}
  WELCOME_CHANNEL_ID: {{ .Values.secrets.WELCOME_CHANNEL_ID | quote }}