name: Deploy commands & update server

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    packages: write

env:
    REGISTRY: ghcr.io
    USER: romeronet
    REPOSITORY: inadaptabot

jobs:
    build-bot:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            
            - name: Set up BuildX
              uses: docker/setup-buildx-action@v4

            - name: Log in to Github Registry
              uses: docker/login-action@v4
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v7
              with:
                context: .
                file: Dockerfile
                platforms: linux/arm64
                push: true
                tags: ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.REPOSITORY }}:latest
    
    deploy:
        runs-on: ubuntu-latest
        needs:
          - build-bot
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            
            - name: Set up kubectl
              uses: azure/setup-kubectl@v5
            
            - name: Set up helm
              uses: azure/setup-helm@v5

            - name: Set up kubeconfig
              run: mkdir -p ~/.kube && echo "${{ secrets.KUBECTL_CONTENT }}" > ~/.kube/config

            - name: Deploy to Kubernetes using helm
              run: |
                helm upgrade --install -n inadaptabot inadaptabot helm \
                  --set-string sha=${{ github.sha }} \
                  --set-string secrets.TOKEN=${{ secrets.TOKEN }} \
                  --set-string secrets.CLIENT_ID=${{ secrets.CLIENT_ID }} \
                  --set-string secrets.WELCOME_CHANNEL_ID=${{ secrets.WELCOME_CHANNEL_ID }}